name: Poetry run tox

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install project with poetry
      run: |
        poetry install
    - name: Run tox linting
      run: |
        poetry run tox -e linting
    - name: Run tox typing
      run: |
        poetry run tox -e typing
    - name: Run isort and black checks
      run: |
        poetry run isort --diff --check --settings-path pyproject.toml ./financify/
        poetry run black --diff --check --config pyproject.toml ./financify/
