name: Pull Request CI

on:
    pull_request:
      branches:
        - main

jobs:
    changelog_updates:
        uses: ./.github/workflows/changelog_updates.yml

    tox:
        uses: ./.github/workflows/poetry_run_tox.yml